<?php
// Copyright 1999-2018. Plesk International GmbH. All rights reserved.
?>

<div id="welcome">
    <?php echo $this->lmsg('index.config.label.preset'); ?>
    <div class="welcome-preset-buttons">
        <?php echo $this->renderSmallTools($this->presetSelector); ?>
    </div>
    <div class="help-popup-link">
        <a href="javascript:openHelpPopup()"><?php echo pm_Locale::lmsg('index.config.help.link'); ?></a>
    </div>
    <?php echo $this->form; ?>
</div>

<script>
    function welcomeLoadPreset(preset)
    {
        new Ajax.Request('/modules/welcome/index.php/index/preset', {
            method: 'get',
            parameters: {
                'preset': preset
            },
            onSuccess: function(transport) {
                var ta = document.getElementById('json');

                ta.value = transport.responseText;
            },
            onFailure: function() {
                alert('ERROR: Unable to get configuration preset contents');
            }
        });
    }

    function openHelpPopup()
    {
        new Jsw.Popup({
            title: '<?php echo pm_Locale::lmsg('index.config.help.popup.title'); ?>',
            popupCls: 'popup-panel u-popup',
            content: `<?php echo $this->help; ?>`,
            buttons: [
                {
                    title: '<?php echo pm_Locale::lmsg('index.config.help.popup.close'); ?>',
                    class: 'u-popup-btn',
                    handler: function(event, popup) {
                        popup.hide();
                    }
                }]
        });
    }
</script>
