<!-- TODO This is just for testing, should be emptied once ready for release! -->
<div id="ext-welcome-app"></div>
<script>
require(['<?= \pm_Context::getBaseUrl() ?>js/main.js'], function (render) {
    render(document.getElementById('ext-welcome-app'), <?= json_encode([
        'locale' => \pm_Locale::getCode(),
        'data'   => (new \PleskExt\Welcome\Config())->getProcessedConfigData(),
    ]) ?>);
});
</script>
